language: cpp

notifications:
  email: false

script:   
- cmake -H. -B_build
- cmake --build _build
- mkdir -p artifacts && cd artifacts
- ../_build/explorer ../explorer/file_01.dat ../explorer/file_02.dat ../explorer/file_03.dat ../explorer/file_04.dat ../explorer/file_05.dat
- cat log.txt
